// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.6
// source: math.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MathService_Sqr_FullMethodName  = "/math.MathService/Sqr"
	MathService_Fact_FullMethodName = "/math.MathService/Fact"
	MathService_Fib_FullMethodName  = "/math.MathService/Fib"
)

// MathServiceClient is the client API for MathService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MathServiceClient interface {
	Sqr(ctx context.Context, in *NumberRequest, opts ...grpc.CallOption) (*NumberReply, error)
	Fact(ctx context.Context, in *NumberRequest, opts ...grpc.CallOption) (*NumberReply, error)
	Fib(ctx context.Context, in *NumberRequest, opts ...grpc.CallOption) (*NumberReply, error)
}

type mathServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMathServiceClient(cc grpc.ClientConnInterface) MathServiceClient {
	return &mathServiceClient{cc}
}

func (c *mathServiceClient) Sqr(ctx context.Context, in *NumberRequest, opts ...grpc.CallOption) (*NumberReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NumberReply)
	err := c.cc.Invoke(ctx, MathService_Sqr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mathServiceClient) Fact(ctx context.Context, in *NumberRequest, opts ...grpc.CallOption) (*NumberReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NumberReply)
	err := c.cc.Invoke(ctx, MathService_Fact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mathServiceClient) Fib(ctx context.Context, in *NumberRequest, opts ...grpc.CallOption) (*NumberReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NumberReply)
	err := c.cc.Invoke(ctx, MathService_Fib_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MathServiceServer is the server API for MathService service.
// All implementations must embed UnimplementedMathServiceServer
// for forward compatibility.
type MathServiceServer interface {
	Sqr(context.Context, *NumberRequest) (*NumberReply, error)
	Fact(context.Context, *NumberRequest) (*NumberReply, error)
	Fib(context.Context, *NumberRequest) (*NumberReply, error)
	mustEmbedUnimplementedMathServiceServer()
}

// UnimplementedMathServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMathServiceServer struct{}

func (UnimplementedMathServiceServer) Sqr(context.Context, *NumberRequest) (*NumberReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Sqr not implemented")
}
func (UnimplementedMathServiceServer) Fact(context.Context, *NumberRequest) (*NumberReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Fact not implemented")
}
func (UnimplementedMathServiceServer) Fib(context.Context, *NumberRequest) (*NumberReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Fib not implemented")
}
func (UnimplementedMathServiceServer) mustEmbedUnimplementedMathServiceServer() {}
func (UnimplementedMathServiceServer) testEmbeddedByValue()                     {}

// UnsafeMathServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MathServiceServer will
// result in compilation errors.
type UnsafeMathServiceServer interface {
	mustEmbedUnimplementedMathServiceServer()
}

func RegisterMathServiceServer(s grpc.ServiceRegistrar, srv MathServiceServer) {
	// If the following call panics, it indicates UnimplementedMathServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MathService_ServiceDesc, srv)
}

func _MathService_Sqr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServiceServer).Sqr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MathService_Sqr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServiceServer).Sqr(ctx, req.(*NumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MathService_Fact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServiceServer).Fact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MathService_Fact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServiceServer).Fact(ctx, req.(*NumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MathService_Fib_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServiceServer).Fib(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MathService_Fib_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServiceServer).Fib(ctx, req.(*NumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MathService_ServiceDesc is the grpc.ServiceDesc for MathService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MathService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "math.MathService",
	HandlerType: (*MathServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sqr",
			Handler:    _MathService_Sqr_Handler,
		},
		{
			MethodName: "Fact",
			Handler:    _MathService_Fact_Handler,
		},
		{
			MethodName: "Fib",
			Handler:    _MathService_Fib_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "math.proto",
}
