// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: math.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberRequest) Reset() {
	*x = NumberRequest{}
	mi := &file_math_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberRequest) ProtoMessage() {}

func (x *NumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_math_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberRequest.ProtoReflect.Descriptor instead.
func (*NumberRequest) Descriptor() ([]byte, []int) {
	return file_math_proto_rawDescGZIP(), []int{0}
}

func (x *NumberRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type NumberReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int64                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberReply) Reset() {
	*x = NumberReply{}
	mi := &file_math_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberReply) ProtoMessage() {}

func (x *NumberReply) ProtoReflect() protoreflect.Message {
	mi := &file_math_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberReply.ProtoReflect.Descriptor instead.
func (*NumberReply) Descriptor() ([]byte, []int) {
	return file_math_proto_rawDescGZIP(), []int{1}
}

func (x *NumberReply) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_math_proto protoreflect.FileDescriptor

const file_math_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"math.proto\x12\x04math\"'\n" +
	"\rNumberRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\"%\n" +
	"\vNumberReply\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x03R\x06number2\x9b\x01\n" +
	"\vMathService\x12-\n" +
	"\x03Sqr\x12\x13.math.NumberRequest\x1a\x11.math.NumberReply\x12.\n" +
	"\x04Fact\x12\x13.math.NumberRequest\x1a\x11.math.NumberReply\x12-\n" +
	"\x03Fib\x12\x13.math.NumberRequest\x1a\x11.math.NumberReplyB\x17\n" +
	"\bcom.mathP\x01Z\t/protobufb\x06proto3"

var (
	file_math_proto_rawDescOnce sync.Once
	file_math_proto_rawDescData []byte
)

func file_math_proto_rawDescGZIP() []byte {
	file_math_proto_rawDescOnce.Do(func() {
		file_math_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_math_proto_rawDesc), len(file_math_proto_rawDesc)))
	})
	return file_math_proto_rawDescData
}

var file_math_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_math_proto_goTypes = []any{
	(*NumberRequest)(nil), // 0: math.NumberRequest
	(*NumberReply)(nil),   // 1: math.NumberReply
}
var file_math_proto_depIdxs = []int32{
	0, // 0: math.MathService.Sqr:input_type -> math.NumberRequest
	0, // 1: math.MathService.Fact:input_type -> math.NumberRequest
	0, // 2: math.MathService.Fib:input_type -> math.NumberRequest
	1, // 3: math.MathService.Sqr:output_type -> math.NumberReply
	1, // 4: math.MathService.Fact:output_type -> math.NumberReply
	1, // 5: math.MathService.Fib:output_type -> math.NumberReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_math_proto_init() }
func file_math_proto_init() {
	if File_math_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_math_proto_rawDesc), len(file_math_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_math_proto_goTypes,
		DependencyIndexes: file_math_proto_depIdxs,
		MessageInfos:      file_math_proto_msgTypes,
	}.Build()
	File_math_proto = out.File
	file_math_proto_goTypes = nil
	file_math_proto_depIdxs = nil
}
